name: Publish

on:
  release:
    types:
      - published

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    # Initializes the env variables. These get set after the repo is checked out
    # because they depend on files in the repo.
    env:
      NODE_VERSION: ''

    steps:
      # Checks-out repo.
      - name: Checkout Repo
        id: checkout_repo
        uses: actions/checkout@v4

      # Sets the environment variables from the env.sh script.
      - name: Set Environment Variables
        id: set_env_vars
        run: .github/workflows/scripts/env.sh

      # Sets up Node.
      - name: Setup Node
        id: setup_node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: 'https://registry.npmjs.org'

      # Installs npm dependencies.
      - name: Install
        id: install
        run: npm install

			# Generates syntax.
      - name: Generate Syntax
        id: generate-syntax
        run: npm run generate-syntax -- --verbose

      # Runs a build.
      - name: Build
        id: build
        run: npm run build

      # Publish public package to NPM.
      - name: Publish
        id: publish
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
